server {
    listen 8080;          # nginx non-root (image unprivileged) -> port 8080
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React Router : toute route inconnue retombe sur index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Petit endpoint de sante (utile pour les healthchecks / le futur DAST)
    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }
}